name: DGamxTools
version: '${version}'
main: com.dgamxtools.DGamxTools
api-version: '1.20'
commands:
  Gamemode:
    permission: DGamxTools.Administrator
    aliases: gm
    #游戏模式调整
  Crash:
    permission: DGamxTools.Administrator
    #崩端系统

